#!/bin/bash

set -e

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
ZIP_NAME="foxtown-app.zip"
TEMP_DIR=$(mktemp -d)
EXTRACT_DIR="$TEMP_DIR/foxtown-app"

echo "📦 Copying repo to temp directory..."
cp -r "$PROJECT_DIR" "$EXTRACT_DIR"

cd "$EXTRACT_DIR"

echo "🔍 Scanning for AI markers in code..."
MARKERS=0

# Search for common AI markers (Claude, Cursor, etc)
for file in $(find "$EXTRACT_DIR" -type f \( -name "*.rs" -o -name "*.js" -o -name "*.ts" -o -name "*.tsx" -o -name "*.toml" \) 2>/dev/null); do
  if grep -q "Claude\|Co-Authored-By\|Generated by\|Anthropic\|cursor\.ai\|Cursor IDE" "$file" 2>/dev/null; then
    echo "  Found in: $file"
    MARKERS=$((MARKERS + 1))
  fi
done

# Check for Cursor config files
if find "$EXTRACT_DIR" -type f -name ".cursor*" -o -name "*.cursor" 2>/dev/null | grep -q .; then
  echo "  Found Cursor config files"
  MARKERS=$((MARKERS + 1))
fi

if [ $MARKERS -eq 0 ]; then
  echo "✓ No AI/Cursor markers found"
else
  echo "⚠️  Found $MARKERS potential marker(s) - review manually"
fi

echo "📦 Creating zip file..."
cd "$TEMP_DIR"
zip -r -q "$PROJECT_DIR/$ZIP_NAME" foxtown-app \
  -x "foxtown-app/.git/*" \
  "foxtown-app/clean-zip.sh" \
  "foxtown-app/target/*" \
  "foxtown-app/node_modules/*" \
  "foxtown-app/.claude/*" \
  "foxtown-app/CLAUDE.md" \
  "foxtown-app/ADMIN_API.md" \
  "foxtown-app/PARKING_API.md" \
  "foxtown-app/TESTING.md" \
  "foxtown-app/.gitignore" \
  "foxtown-app/demo.png"

echo "✅ Done! Created: $ZIP_NAME"
echo "📊 Size: $(du -h "$PROJECT_DIR/$ZIP_NAME" | cut -f1)"
echo "📍 Location: $PROJECT_DIR/$ZIP_NAME"

rm -rf "$TEMP_DIR"
